# Generated by Django 4.2 on 2023-04-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedration',
            name='booked',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='Card.kickcard'),
        ),
    ]
